"""create provider_usage table

Revision ID: fcbff531a1d1
Revises: 9940c429945f
Create Date: 2026-06-25 21:05:27.390137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbff531a1d1'
down_revision: Union[str, Sequence[str], None] = '9940c429945f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_usage',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_usage_created_at'), 'provider_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_usage_user_id'), 'provider_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_usage_user_id'), table_name='provider_usage')
    op.drop_index(op.f('ix_provider_usage_created_at'), table_name='provider_usage')
    op.drop_table('provider_usage')
    # ### end Alembic commands ###
